name: Generate Pac-Man snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate Pac-Man snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          palette: '{"hue":"120","tail":"#00ff00","head":"#ffed00"}' # Set the snake to be green and Pac-Man-like
          template: '{"branding":false,"minTail":2,"growth":"fixed","margin":12,"colorize":"palette","autoRotate":false,"scale":12,"fig":"pacman"}' # Customize the SVG to resemble Pac-Man

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
