name: Snake Feeder

on:
  schedule:
    - cron: '0 0 * * *' # Run the action once a day
  workflow_dispatch: # Allow manual triggering

jobs:
  feed-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Snake Feeder action
        uses: ./snake_feeder_action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
