name: Check Weekly Commits

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  check_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Commits
        id: count_commits
        run: |
          git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          COMMITS=$(git log --format='%H' --since='1 week ago' | wc -l)
          echo "::set-output name=commit_count::$COMMITS"

      - name: Fetch GIFs
        uses: actions/checkout@v2
        with:
          ref: output

      - name: Update README
        run: |
          if [ ${{ steps.count_commits.outputs.commit_count }} -lt 10 ]; then
            echo "![Less Than 10 Commits](less_than_10.gif)" > README.md
          else
            echo "![More Than 10 Commits](snake.svg)" > README.md
          fi
          git add README.md
          git commit -m "Update README with commit count"
          git push
